import Room, { RoomType } from '@/models/room';

const rooms: Room[] = [
  {
      id: '1',
      name: 'Deluxe Ocean View',
      slug: 'deluxe-ocean-view',
      type: RoomType.DELUXE_ROOM,
      description: 'A luxurious room with stunning ocean views, featuring floor-to-ceiling windows that allow natural light to flood the space. Enjoy a private balcony where you can sip your morning coffee while watching the sunrise over the horizon. The room is elegantly furnished with a king-sized bed, plush seating area, and a modern en-suite bathroom equipped with a soaking tub and rain shower.',
      summary: 'Experience the beauty of the ocean from your room.',
      location: {
          address: '123 Beach Ave',
          city: 'Miami',
          state: 'FL',
          zip: '33139',
          latitude: 25.7617,
          longitude: -80.1918,
      },
      amenities: [
          { label: 'Free WiFi', icon: 'wifi' },
          { label: 'Pool Access', icon: 'pool' },
      ],
      price: 150000,
      slashedPrice: 180000,
      images: [
          '/images/rooms/deluxe-ocean-view-room1.png',
          '/images/rooms/deluxe-ocean-view-room2.png',
          '/images/rooms/deluxe-ocean-view-room3.png',
          '/images/rooms/deluxe-ocean-view-room4.png',
          '/images/rooms/deluxe-ocean-view-room5.png',
      ],
      videos: ['video1.mp4'],
      availability: [{ checkIn: 1, checkOut: 7 }],
      bedroom: 1,
      bathroom: 1,
      currency: 'NGN',
      rate: 5,
      status: 'active',
      rules: ['No smoking', 'No pets'],
      safeties: [
          { title: 'Fire Alarm', body: 'Smoke detectors installed.', icon: 'fire' },
      ],
      createdAt: 1737527058778,
      updatedAt: 1737527058778,
      guest: 2,
      size: 400
  },
  {
    id: '2',
    name: 'Single Room',
    slug: 'single-room',
    type: RoomType.SINGLE_ROOM,
    description: 'A cozy room perfect for solo travelers, designed with comfort and functionality in mind. The room features a comfortable queen-sized bed, a work desk with ample lighting, and a private bathroom. Enjoy modern amenities such as a flat-screen TV, mini-fridge, and complimentary coffee-making facilities. The decor is warm and inviting, making it an ideal retreat after a day of exploring the city.',
    summary: 'Ideal for a comfortable stay.',
    location: {
      address: '456 City St',
      city: 'New York',
      state: 'NY',
      zip: '10001',
      latitude: 40.7128,
      longitude: -74.006,
    },
    amenities: [
      { label: 'Free Breakfast', icon: 'breakfast' },
      { label: 'Gym Access', icon: 'gym' },
    ],
    price: 85000,
    images: [
      '/images/rooms/Single-Room.jpg',
      '/images/rooms/deluxe-ocean-view-room2.png',
      '/images/rooms/deluxe-ocean-view-room3.png',
      '/images/rooms/deluxe-ocean-view-room4.png',
      '/images/rooms/deluxe-ocean-view-room5.png',
    ],
    videos: [],
    availability: [{ checkIn: 1, checkOut: 3 }],
    bedroom: 1,
    bathroom: 1,
    currency: 'NGN',
    rate: 4,
    status: 'active',
    rules: ['No parties', 'Quiet hours after 10 PM'],
    safeties: [],
    createdAt: 1737527058778,
    updatedAt: 1737527058778,
    guest: 1,
    size: 250
  },
  {
    id: '3',
    name: 'Super Room',
    slug: 'super-room',
    type: RoomType.SUPER_ROOM,
    description: 'Spacious room with modern amenities, perfect for guests seeking a blend of luxury and comfort. The room includes a king-sized bed, a large seating area with a sofa, and a stylish workspace. The en-suite bathroom features a walk-in shower and premium toiletries. Guests can enjoy stunning views of the city skyline from the large windows, making it a perfect choice for both relaxation and productivity.',
    summary: 'Enjoy a luxurious stay with extra space.',
    location: {
      address: '789 Luxury Blvd',
      city: 'Los Angeles',
      state: 'CA',
      zip: '90001',
      latitude: 34.0522,
      longitude: -118.2437,
    },
    amenities: [
      { label: 'Spa Access', icon: 'spa' },
      { label: 'Room Service', icon: 'service' },
    ],
    price: 250000,
    images: [
      '/images/rooms/Super-Room.jpg',
      '/images/rooms/deluxe-ocean-view-room2.png',
      '/images/rooms/deluxe-ocean-view-room3.png',
      '/images/rooms/deluxe-ocean-view-room4.png',
      '/images/rooms/deluxe-ocean-view-room5.png',
    ],
    videos: [],
    availability: [{ checkIn: 1, checkOut: 5 }],
    bedroom: 1,
    bathroom: 1,
    currency: 'NGN',
    rate: 5,
    status: 'active',
    rules: ['No smoking', 'No pets'],
    safeties: [],
    createdAt: 1737527058778,
    updatedAt: 1737527058778,
    guest: 2,
    size: 500
  },
  {
    id: '4',
    name: 'Presidential Suite',
    slug: 'presidential-suite',
    type: RoomType.PRESIDENTIAL_ROOM,
    description: 'The ultimate luxury experience, this suite offers unparalleled comfort and elegance. Featuring a spacious living area, a dining table for four, and a private balcony with breathtaking views, this suite is perfect for special occasions. The master bedroom boasts a king-sized bed, while the lavish bathroom includes a whirlpool tub and separate rain shower. Enjoy exclusive access to the hotel\'s premium services and amenities.',
    summary: 'Stay in style with top-notch amenities.',
    location: {
      address: '101 Elite Rd',
      city: 'Las Vegas',
      state: 'NV',
      zip: '89101',
      latitude: 36.1699,
      longitude: -115.1398,
    },
    amenities: [
      { label: 'Private Pool', icon: 'pool' },
      { label: 'Breakfast', icon: 'food' },
      { label: 'Breakfast', icon: 'food' },
      { label: 'Breakfast', icon: 'food' },
      { label: 'Breakfast', icon: 'food' },
      { label: 'Butler Service', icon: 'butler' },
    ],
    price: 750000,
    images: [
      '/images/rooms/Presidential-Room.jpg',
      '/images/rooms/deluxe-ocean-view-room2.png',
      '/images/rooms/deluxe-ocean-view-room3.png',
      '/images/rooms/deluxe-ocean-view-room4.png',
      '/images/rooms/deluxe-ocean-view-room5.png',
    ],
    videos: [],
    availability: [{ checkIn: 1, checkOut: 10 }],
    bedroom: 2,
    bathroom: 2,
    currency: 'NGN',
    rate: 5,
    status: 'active',
    rules: ['No loud music', 'Respect neighbors'],
    safeties: [],
    createdAt: 1737527058778,
    updatedAt: 1737527058778,
    guest: 0,
    size: 1500
  },
  {
    id: '5',
    name: 'Family Room',
    slug: 'family-room',
    type: RoomType.DELUXE_ROOM,
    description: 'Perfect for families with children, this spacious room features two queen-sized beds and a cozy seating area. The room is equipped with child-friendly amenities, including a play area and games. The private bathroom includes a bathtub, making it easy for families to unwind after a day of adventures. Enjoy the convenience of a mini-fridge and microwave for snacks and quick meals.',
    summary: 'Spacious and comfortable for the whole family.',
    location: {
      address: '202 Family St',
      city: 'Orlando',
      state: 'FL',
      zip: '32801',
      latitude: 28.5383,
      longitude: -81.3792,
    },
    amenities: [
      { label: 'Kids Play Area', icon: 'play' },
      { label: 'Free Parking', icon: 'parking' },
    ],
    price: 200000,
    images: [
      '/images/rooms/deluxe-ocean-view-room1.png',
      '/images/rooms/deluxe-ocean-view-room2.png',
      '/images/rooms/deluxe-ocean-view-room3.png',
      '/images/rooms/deluxe-ocean-view-room4.png',
      '/images/rooms/deluxe-ocean-view-room5.png',
    ],
    videos: [],
    availability: [{ checkIn: 1, checkOut: 7 }],
    bedroom: 2,
    bathroom: 1,
    currency: 'NGN',
    rate: 4,
    status: 'active',
    rules: ['No smoking', 'Supervise children'],
    safeties: [],
    createdAt: 1737527058778,
    updatedAt: 1737527058778,
    guest: 0,
    size: 0
  },
  {
    id: '6',
    name: 'Romantic Getaway',
    slug: 'romantic-getaway',
    type: RoomType.DELUXE_ROOM,
    description: 'A romantic room for couples, designed to create an intimate atmosphere. The room features a king-sized bed adorned with luxurious linens, a cozy seating area, and soft lighting. Enjoy a private balcony with stunning views, perfect for a candlelit dinner. The en-suite bathroom includes a soaking tub and complimentary bath products to enhance your relaxation experience.',
    summary: 'Enjoy a cozy and intimate atmosphere.',
    location: {
      address: '303 Love Ln',
      city: 'Napa',
      state: 'CA',
      zip: '94558',
      latitude: 38.2975,
      longitude: -122.2869,
    },
    amenities: [
      { label: 'Wine Tasting', icon: 'wine' },
      { label: 'Jacuzzi', icon: 'jacuzzi' },
    ],
    price: 180000,
    images: [
      '/images/rooms/deluxe-ocean-view-room1.png',
      '/images/rooms/deluxe-ocean-view-room2.png',
      '/images/rooms/deluxe-ocean-view-room3.png',
      '/images/rooms/deluxe-ocean-view-room4.png',
      '/images/rooms/deluxe-ocean-view-room5.png',
    ],
    videos: [],
    availability: [{ checkIn: 1, checkOut: 5 }],
    bedroom: 1,
    bathroom: 1,
    currency: 'NGN',
    rate: 5,
    status: 'active',
    rules: ['No parties', 'Quiet hours after 10 PM'],
    safeties: [],
    createdAt: 1737527058778,
    updatedAt: 1737527058778,
    guest: 0,
    size: 0
  },
  {
    id: '7',
    name: 'Business Suite',
    slug: 'business-suite',
    type: RoomType.SUPER_ROOM,
    description: 'Ideal for business travelers, this suite is equipped with everything you need to stay productive. The room features a spacious work desk, high-speed internet access, and a comfortable seating area. The king-sized bed ensures a restful night\'s sleep, while the en-suite bathroom includes a walk-in shower and premium toiletries. Enjoy access to the business lounge for meetings and networking.',
    summary: 'Stay connected with all the amenities you need.',
    location: {
      address: '404 Business Rd',
      city: 'Chicago',
      state: 'IL',
      zip: '60601',
      latitude: 41.8781,
      longitude: -87.6298,
    },
    amenities: [
      { label: 'Conference Room', icon: 'conference' },
      { label: 'High-Speed Internet', icon: 'internet' },
    ],
    price: 280000,
    images: [
      '/images/rooms/Super-Room.jpg',
      '/images/rooms/deluxe-ocean-view-room2.png',
      '/images/rooms/deluxe-ocean-view-room3.png',
      '/images/rooms/deluxe-ocean-view-room4.png',
      '/images/rooms/deluxe-ocean-view-room5.png',
    ],
    videos: [],
    availability: [{ checkIn: 1, checkOut: 3 }],
    bedroom: 1,
    bathroom: 1,
    currency: 'NGN',
    rate: 4,
    status: 'active',
    rules: ['No loud music', 'Respect neighbors'],
    safeties: [],
    createdAt: 1737527058778,
    updatedAt: 1737527058778,
    guest: 0,
    size: 0
  },
  {
    id: '8',
    name: 'Eco-Friendly Room',
    slug: 'eco-friendly-room',
    type: RoomType.SINGLE_ROOM,
    description: 'A sustainable room with eco-friendly amenities, designed for the environmentally conscious traveler. The room features organic bedding, energy-efficient lighting, and a mini-fridge stocked with local organic snacks. Enjoy a private bathroom with eco-friendly toiletries and a shower that uses water-saving technology. The decor is inspired by nature, creating a calming atmosphere for relaxation.',
    summary: 'Stay green while enjoying comfort.',
    location: {
      address: '505 Green St',
      city: 'Portland',
      state: 'OR',
      zip: '97201',
      latitude: 45.5155,
      longitude: -122.6793,
    },
    amenities: [
      { label: 'Solar Power', icon: 'solar' },
      { label: 'Organic Breakfast', icon: 'breakfast' },
    ],
    price: 120000,
    images: [
      '/images/rooms/Single-Room.jpg',
      '/images/rooms/deluxe-ocean-view-room2.png',
      '/images/rooms/deluxe-ocean-view-room3.png',
      '/images/rooms/deluxe-ocean-view-room4.png',
      '/images/rooms/deluxe-ocean-view-room5.png',
    ],
    videos: [],
    availability: [{ checkIn: 1, checkOut: 3 }],
    bedroom: 1,
    bathroom: 1,
    currency: 'NGN',
    rate: 4,
    status: 'active',
    rules: ['No smoking', 'Recycle waste'],
    safeties: [],
    createdAt: 1737527058778,
    updatedAt: 1737527058778,
    guest: 0,
    size: 0
  },
  {
    id: '9',
    name: 'Luxury Cabin',
    slug: 'luxury-cabin',
    type: RoomType.DELUXE_ROOM,
    description: 'A cabin in the woods with luxury amenities, offering a unique blend of rustic charm and modern comfort. The room features a king-sized bed, a cozy fireplace, and large windows that provide breathtaking views of the surrounding forest. The en-suite bathroom includes a soaking tub and a separate shower. Enjoy outdoor activities with easy access to hiking trails and ski slopes, making it perfect for nature lovers.',
    summary: 'Experience nature without sacrificing comfort.',
    location: {
      address: '606 Cabin Rd',
      city: 'Aspen',
      state: 'CO',
      zip: '81611',
      latitude: 39.1911,
      longitude: -106.8175,
    },
    amenities: [
      { label: 'Fireplace', icon: 'fireplace' },
      { label: 'Ski Access', icon: 'ski' },
    ],
    price: 350000,
    images: [
      '/images/rooms/deluxe-ocean-view-room1.png',
      '/images/rooms/deluxe-ocean-view-room2.png',
      '/images/rooms/deluxe-ocean-view-room3.png',
      '/images/rooms/deluxe-ocean-view-room4.png',
      '/images/rooms/deluxe-ocean-view-room5.png',
    ],
    videos: [],
    availability: [{ checkIn: 1, checkOut: 7 }],
    bedroom: 2,
    bathroom: 2,
    currency: 'NGN',
    rate: 5,
    status: 'active',
    rules: ['No loud music', 'Respect nature'],
    safeties: [],
    createdAt: 1737527058778,
    updatedAt: 1737527058778,
    guest: 0,
    size: 0
  },
  {
    id: '10',
    name: 'Historic Room',
    slug: 'historic-room',
    type: RoomType.SINGLE_ROOM,
    description: 'A room with a rich history and vintage decor, offering a unique glimpse into the past. The room features antique furnishings, a queen-sized bed, and a private bathroom with modern amenities. Enjoy the charm of original artwork and historical artifacts that tell the story of the building. This room is perfect for those who appreciate history while enjoying contemporary comforts.',
    summary: 'Step back in time while enjoying modern comforts.',
    location: {
      address: '707 History St',
      city: 'Philadelphia',
      state: 'PA',
      zip: '19101',
      latitude: 39.9526,
      longitude: -75.1652,
    },
    amenities: [
      { label: 'Guided Tours', icon: 'tour' },
      { label: 'Complimentary Snacks', icon: 'snack' },
    ],
    price: 130000,
    images: [
      '/images/rooms/Single-Room.jpg',
      '/images/rooms/deluxe-ocean-view-room2.png',
      '/images/rooms/deluxe-ocean-view-room3.png',
      '/images/rooms/deluxe-ocean-view-room4.png',
      '/images/rooms/deluxe-ocean-view-room5.png',
    ],
    videos: [],
    availability: [{ checkIn: 1, checkOut: 3 }],
    bedroom: 1,
    bathroom: 1,
    currency: 'NGN',
    rate: 4,
    status: 'active',
    rules: ['No smoking', 'Respect the property'],
    safeties: [],
    createdAt: 1737527058778,
    updatedAt: 1737527058778,
    guest: 0,
    size: 0
  },
];

export default rooms;
